version: 2.1

workflows:
  buildapp:
    jobs:
      - build-one-ios

jobs:
  build-one-ios:
    macos:
      xcode: 13.3 # Specify the Xcode version to use

    steps:
      - checkout

      - run:
          name: Build Cosmos Project
          command: |
            export ANDROID_SDK_ROOT=/usr/local/share/android-commandlinetools/cmdline-tools/latest/bin
            ./gradlew cosmos-bundled:createXCFramework
